/* Generated By:JavaCC: Do not edit this line. zmsql4Constants.java */
package zmsqlParse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface zmsql4Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 5;
  /** RegularExpression Id. */
  int FLOAT = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int BOOL = 8;
  /** RegularExpression Id. */
  int TRUE = 9;
  /** RegularExpression Id. */
  int FALSE = 10;
  /** RegularExpression Id. */
  int UNIQUE = 11;
  /** RegularExpression Id. */
  int NOTNULL = 12;
  /** RegularExpression Id. */
  int PRIMARYKEY = 13;
  /** RegularExpression Id. */
  int SQLDEFAULT = 14;
  /** RegularExpression Id. */
  int CHECK = 15;
  /** RegularExpression Id. */
  int CONSTRAINT = 16;
  /** RegularExpression Id. */
  int FOREIGNKEY = 17;
  /** RegularExpression Id. */
  int REFERENCES = 18;
  /** RegularExpression Id. */
  int NOACTION = 19;
  /** RegularExpression Id. */
  int RESTRICT = 20;
  /** RegularExpression Id. */
  int SETNULL = 21;
  /** RegularExpression Id. */
  int CASCADE = 22;
  /** RegularExpression Id. */
  int ON = 23;
  /** RegularExpression Id. */
  int DELETE = 24;
  /** RegularExpression Id. */
  int UPDATE = 25;
  /** RegularExpression Id. */
  int INSERT = 26;
  /** RegularExpression Id. */
  int CREATE = 27;
  /** RegularExpression Id. */
  int DROP = 28;
  /** RegularExpression Id. */
  int SELECT = 29;
  /** RegularExpression Id. */
  int TABLE = 30;
  /** RegularExpression Id. */
  int WHERE = 31;
  /** RegularExpression Id. */
  int INTO = 32;
  /** RegularExpression Id. */
  int VALUES = 33;
  /** RegularExpression Id. */
  int SET = 34;
  /** RegularExpression Id. */
  int FROM = 35;
  /** RegularExpression Id. */
  int ADD = 36;
  /** RegularExpression Id. */
  int MINUS = 37;
  /** RegularExpression Id. */
  int DIVIDE = 38;
  /** RegularExpression Id. */
  int MOD = 39;
  /** RegularExpression Id. */
  int GREAT = 40;
  /** RegularExpression Id. */
  int LESS = 41;
  /** RegularExpression Id. */
  int EQUAL = 42;
  /** RegularExpression Id. */
  int AND = 43;
  /** RegularExpression Id. */
  int OR = 44;
  /** RegularExpression Id. */
  int NOT = 45;
  /** RegularExpression Id. */
  int ICONSTANT = 46;
  /** RegularExpression Id. */
  int FCONSTANT = 47;
  /** RegularExpression Id. */
  int IDENTIFIER = 48;
  /** RegularExpression Id. */
  int SCONSTANT = 49;
  /** RegularExpression Id. */
  int LETTER = 50;
  /** RegularExpression Id. */
  int DIGIT = 51;
  /** RegularExpression Id. */
  int EOL = 52;
  /** RegularExpression Id. */
  int MULTIPLY = 53;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"int\"",
    "\"float\"",
    "\"string\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"unique\"",
    "\"not null\"",
    "\"primary key\"",
    "\"sqldefault\"",
    "\"check\"",
    "\"constraint\"",
    "\"foreign key\"",
    "\"references\"",
    "\"no action\"",
    "\"restrict\"",
    "\"set null\"",
    "\"cascade\"",
    "\"on\"",
    "\"delete\"",
    "\"update\"",
    "\"insert\"",
    "\"create\"",
    "\"drop\"",
    "\"select\"",
    "\"table\"",
    "\"where\"",
    "\"into\"",
    "\"values\"",
    "\"set\"",
    "\"from\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "<ICONSTANT>",
    "<FCONSTANT>",
    "<IDENTIFIER>",
    "<SCONSTANT>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"=\"",
  };

}
