/* Generated By:JavaCC: Do not edit this line. zmsqlConstants.java */
package zmsqlParse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface zmsqlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ACH = 5;
  /** RegularExpression Id. */
  int BCH = 6;
  /** RegularExpression Id. */
  int EOL = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"a\"",
    "\"b\"",
    "\";\"",
  };

}
